{"trial_id": "0011", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units_first", "default": null, "conditions": [], "min_value": 16, "max_value": 64, "step": 4, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_second", "default": null, "conditions": [], "min_value": 16, "max_value": 64, "step": 4, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_third", "default": null, "conditions": [], "min_value": 16, "max_value": 64, "step": 4, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 0.001, "conditions": [], "min_value": 0.0001, "max_value": 0.01, "step": null, "sampling": "log"}}], "values": {"units_first": 36, "units_second": 60, "units_third": 32, "learning_rate": 0.0023015199802882587, "tuner/epochs": 3, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node compile_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits defined at (most recent call last):\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/ipykernel_launcher.py\", line 17, in <module>\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py\", line 596, in run_forever\n\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py\", line 1890, in _run_once\n\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/events.py\", line 80, in _run\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 542, in dispatch_queue\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 531, in process_one\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 359, in execute_request\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 775, in execute_request\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 446, in do_execute\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n\n  File \"/var/folders/2v/mcgfxq4d2_n2639c1xhyd92w0000gn/T/ipykernel_33957/2134660025.py\", line 13, in <module>\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 325, in fit\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 118, in one_step_on_iterator\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 106, in one_step_on_data\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 60, in train_step\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/trainers/trainer.py\", line 322, in compute_loss\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/trainers/compile_utils.py\", line 605, in __call__\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/trainers/compile_utils.py\", line 641, in call\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/losses/loss.py\", line 42, in __call__\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/losses/losses.py\", line 22, in call\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/losses/losses.py\", line 1714, in sparse_categorical_crossentropy\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/ops/nn.py\", line 1554, in sparse_categorical_crossentropy\n\n  File \"/Users/bradymitchelmore/Library/Mobile Documents/com~apple~CloudDocs/MUN/Year 3/Term 7/COMP 3401/Assignments/comp3401/lib/python3.9/site-packages/keras/src/backend/tensorflow/nn.py\", line 633, in sparse_categorical_crossentropy\n\nlogits must be 2-D, but got shape [0]\n\t [[{{node compile_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_one_step_on_iterator_7164347]\n"}